# Generated by Django 4.2.25 on 2025-10-25 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='role',
            field=models.CharField(default='未設定', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='comparison.work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='未設定', max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
