# Generated by Django 5.2.7 on 2025-10-29 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0003_alter_tag_user_alter_tag_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='comparison.work'),
        ),
    ]
