# Generated by Django 5.2.7 on 2025-10-29 04:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0005_meta_alter_tag_user_alter_tag_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['role', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('work', 'user', 'role', 'name')},
        ),
    ]
