# Generated by Django 5.2.7 on 2025-10-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0007_alter_tag_unique_together_tag_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
