# Generated by Django 5.2.7 on 2025-11-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0008_alter_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, unique=True),
        ),
    ]
