# Generated by Django 5.2.7 on 2025-11-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0009_alter_tag_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='works',
            field=models.ManyToManyField(related_name='tags', through='comparison.WorkTag', through_fields=('tag', 'work'), to='comparison.work'),
        ),
    ]
