# Generated by Django 5.2.7 on 2025-11-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0011_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='comparison_page',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='id_for_anchor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
