# Generated by Django 5.2.7 on 2025-11-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0012_work_comparison_page_work_id_for_anchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='comparison_page',
            field=models.CharField(blank=True, help_text="比較表ファイル名の識別子（例: '01_a'）", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='id_for_anchor',
            field=models.CharField(blank=True, help_text="比較表HTML内のアンカーID（例: '11eyes'）", max_length=100, null=True),
        ),
    ]
