# Generated by Django 5.2.8 on 2025-11-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0013_alter_work_comparison_page_alter_work_id_for_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktag',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
    ]
